# Coin Price configuration

app:
  name: Coin Price indicator
  description: Coin Price is a crypto curency price indicator applet for Ubuntu
  url: https://github.com
  version: 0.1

author:
  name: Nil Gradisnik
  email: nil.gradisnik@gmail.com
  copyright: Copyright (C) 2014 Nil Gradisnik

default:
  refresh: 30 # seconds
